[master]: WSL improvements.
Removes much of the UBNT & CB specific scripts that were hanging around.

Much added for better WSL support, as that's now primary development
environment.

[master]: Script more package management.

[master]: Add AWS instance credentials script.

[master]: Updates from latest rebuild.

[master]: Typo fix in usage.

[master]: Manage jp with upgrade script.

[master]: Fixup gitconfig.

diff --git a/Linux/bin/gotestcolor b/Linux/bin/gotestcolor
--- a/Linux/bin/gotestcolor
+++ b/Linux/bin/gotestcolor
@@ -1,4 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -euo pipefail
+
 COLOR_RESET=$(tput sgr0)
 COLOR_RUN=$(tput setaf 6)
 COLOR_PASS=$(tput setaf 2)
@@ -6,13 +8,13 @@ COLOR_FAIL=$(tput setaf 1)
 COLOR_UNKNOWN=$(tput setaf 3)
 
 sed -le '
-s/^\(?\)\([ 	].*\)$/'$COLOR_UNKNOWN'\1'$COLOR_RESET'\2/
-s/^\(ok\)\([ 	].*\)$/'$COLOR_PASS'\1'$COLOR_RESET'\2/
-s/^\(FAIL\)\([ 	].*\)$/'$COLOR_FAIL'\1'$COLOR_RESET'\2/
-s/^\(=== RUN\)\(.*\)$/'$COLOR_RUN'\1'$COLOR_RESET'\2/
-s/^\(--- PASS\)\(.*\)$/'$COLOR_PASS'\1'$COLOR_RESET'\2/
-s/^\(--- FAIL\)\(.*\)$/'$COLOR_FAIL'\1'$COLOR_RESET'\2/
-s/^\(PASS\)$/'$COLOR_PASS'\1'$COLOR_RESET'/
-s/^\(FAIL\)$/'$COLOR_FAIL'\1'$COLOR_RESET'/
-s/^\(testing: warning: no tests to run\)$/'$COLOR_UNKNOWN'\1'$COLOR_RESET'/
+s/^\(?\)\([ 	].*\)$/'"${COLOR_UNKNOWN}"'\1'"${COLOR_RESET}"'\2/
+s/^\(ok\)\([ 	].*\)$/'"${COLOR_PASS}"'\1'"${COLOR_RESET}"'\2/
+s/^\(FAIL\)\([ 	].*\)$/'"${COLOR_FAIL}"'\1'"${COLOR_RESET}"'\2/
+s/^\(=== RUN\)\(.*\)$/'"${COLOR_RUN}"'\1'"${COLOR_RESET}"'\2/
+s/^\(--- PASS\)\(.*\)$/'"${COLOR_PASS}"'\1'"${COLOR_RESET}"'\2/
+s/^\(--- FAIL\)\(.*\)$/'"${COLOR_FAIL}"'\1'"${COLOR_RESET}"'\2/
+s/^\(PASS\)$/'"${COLOR_PASS}"'\1'"${COLOR_RESET}"'/
+s/^\(FAIL\)$/'"${COLOR_FAIL}"'\1'"${COLOR_RESET}"'/
+s/^\(testing: warning: no tests to run\)$/'"${COLOR_UNKNOWN}"'\1'"${COLOR_RESET}"'/
 '
